### ISSUE TITLE
Remove中next的判断缺少等于号

### ISSUE THREAD

**Issue by lkysyzxz** [youshuaixing/FixedDictionary#1]
594 ： if (next > 0) //有后继元素，把后继元素放到当前位置，再移除原后继元素位置的内容
594 ： if (next >= 0) //有后继元素，把后继元素放到当前位置，再移除原后继元素位置的内容
没有元素时next=-1
这是边界情况

**Comment by youshuaixing** [comment]
if (next >= 0)//if(next != -1) //有后继元素，把后继元素放到当前位置，再移除原后继元素位置的内容
