### ISSUE TITLE
Insert中freeNode的更新有误

### ISSUE THREAD

**Issue by lkysyzxz** [youshuaixing/FixedDictionary#2]
一个建议：
       379行 可以直接写成targetBucket - count
Insert逻辑中，FreeNode的计算错误，建议用下面这组测试用例断点调试：
dict.Add(537919495, 0);
dict.Add(8,0);
dict.Add(538443782,0);
dict.Add(538705925,0);
dict.Add(538836996,0);
dict.Add(572391427,0);
dict.Add(572391426, 0);

发现的问题是边界条件freeNode == count的情况没有考虑到，If判断很多，可以把Insert逻辑整理一下

**Comment by youshuaixing** [comment]
solution：
if(targetBucket+1 > count)
{if (freeCount == 0) freeNode = count; //freeCount==0说明之前的freeNode也是错的。这么更新，除非下面的freeCount==0时候是错误的，其他是正确的 }
