### ISSUE TITLE
Insert中FreeNode的更新逻辑存在极端情况的Bug

### ISSUE THREAD

**Issue by lkysyzxz** [youshuaixing/FixedDictionary#3]
在第二种情况和第三种情况中，FreeNode的更新是从FreeNode+1开始往count的方向遍历更新的
这样会有一种极端的情况，下面的样例就可以复现。
``` C#
//  这会导致数组长度初始化为7
FixedDictionary<uint, byte> dict = new FixedDictionary<uint, byte>(5);
dict.Add(6, 0);
dict.Add(5, 0);
dict.Add(4, 0);
dict.Add(3, 0);
dict.Add(2, 0);
dict.Add(1, 0);
dict.Add(0, 0);
dict.Remove(5);
```
跑上面这组代码，删除5之前，FreeNode为0
删除5之后，FreeNode还是0，但FreeCount变为了1，FreeNode指向了一个非空闲的位置
这会导致后续再插入新节点时，覆盖掉一个非空闲位置的节点。
进而会引发链表成环的情况

**Comment by youshuaixing** [comment]
solution：freeNode = (freeCount <= 0) ? next : (next < freeNode ? next : freeNode); //这里有个问题，当freeCount==0时，freeNode也是指向的0
